### ISSUE TITLE
Mac and Windows shortcut is mixed 

### ISSUE THREAD

**Issue by shixiaoyu** [mohnish/rearrange-tabs#30]
Versions: 
On Mac High Sierra 10.13.2 (17C205
Rearrange Tabs 2.1.6
Version 69.0.3497.100 (Official Build) (64-bit)

In the chrome address bar, If you use alt + shrift + left|right arrow, it acts like ctrl + shift + left|right arrow, where it moves tab around instead of marking the text in the address bar. Suspect there is some bugs that mixed windows and mac shortcuts.

**Comment by mohnish** [comment]
Hello @shixiaoyu, thanks for taking time to open this issue. Currently, this is a known issue https://github.com/mohnish/rearrange-tabs/issues/27

I believe the bug has nothing to do with the extension itself, since, the shortcuts are only defined in the [manifest.json](https://github.com/mohnish/rearrange-tabs/blob/1bd68584b8d6b24821fc80fadd96940e1f91c029/manifest.json#L13-L42) and it looks like it's a bug in Chrome (>= 69) itself. For now, the only workaround is to override the shortcut from `chrome://extensions/shortcuts` to a different one. I've contacted the support team and they haven't yet responded back to me. I'll post and update and fix the issue as soon as (I can) I find any new information. Thanks for your patience and use of the extension. 

Cheers.

**Comment by mohnish** [comment]
Closing this in favor of this https://github.com/mohnish/rearrange-tabs/issues/27, just so we have all the discussion at one place.
