### ISSUE TITLE
Click extension icon to move tab to the far right?

### ISSUE THREAD

**Issue by orschiro** [mohnish/rearrange-tabs#32]
Dear @mohnish,

Your work on this extension is very much appreciated!

I have a request. 

Would you be able to implement a feature by which clicking the extension icon would move the active tab to the far right?

Yours

**Comment by orschiro** [comment]
@mohnish any update on this? :-)

Cheers!

**Comment by mohnish** [comment]
@orschiro You can currently configure your keyboard shortcut to do that `chrome://extensions/shortcuts`. But, I'm afraid clicking on the icon can't be supported. This is because, it's hard to convey to the user which action is going to be performed upon clicking the rearrange tabs icon from the toolbar. I feel like configuring a custom shortcut to achieve that is a better option for now.

**Comment by orschiro** [comment]
> This is because, it's hard to convey to the user which action is going to be performed upon clicking the rearrange tabs icon 

What if the user can define this in the options?
