### ISSUE TITLE
option-shift-left / right move tab even when overridden

### ISSUE THREAD

**Issue by lilybguo** [mohnish/rearrange-tabs#44]
Hi! This extension is really great, thank you for making this! 

I'm having an issue with the shortcut. I have already overridden the shortcut to be ctrl-shift+left / right, and that works great. If I'm on a tab, and I click on the URL bar, and try to select a part of the URL, option-shift-left / right move the tab. This does not happen if I do not have the url highlighted. 

I use option-shift-left / right a lot to navigate strings. Is there any way to keep that shortcut? When I disable rearrange tabs it does work again. I'm on BigSur and Chrome version 92. 

In this recording you can see I have set shortcuts. First I use my shortcuts, which work correctly. I try to use option-shift-left and right, and nothing happens. Then I highlight the URL and use option-shift-left / right again, and the tab moves left and right. 

![rearrage_tabs](https://user-images.githubusercontent.com/9200983/130438534-6e900f08-4941-4157-a02c-984fe5300ebf.gif)

Thank you!

**Comment by tommyalvarez** [comment]
+1 to this. Also I want to say I didn't change any shortcut, so not sure why ctrl + shift + left|right + option + shift + left|right are both working.

**Comment by mohnish** [comment]
@lilybguo Firstly, sorry about the late response. I had to deal with some health issues and I'm finally getting back to my regular routine. 

Secondly, this is a known issue. It looks like it has something to do with the way Chrome extension APIs handle keyboard shortcuts natively. Personally, I use *CTRL+CMD+arrowkeys*. This shortcut doesn't hijack any of the existing keyboard shortcuts. The reason why you're experiencing the issue is due to the fact that the default shortcut uses the same combination as highlighting words. Now, I'd except Chrome to fix it at some point, but it has been this way ever since Chrome 69. You can read more about it here: https://github.com/mohnish/rearrange-tabs/issues/27

/cc: @tommyalvarez 

My suggestion is to use the shortcut <kbd>Ctrl</kbd>-<kbd>Cmd</kbd>-<kbd>Left/Right</kbd>

**Comment by lilybguo** [comment]
Thank you 🙏
