### ISSUE TITLE
Allow more symbols in custom shortcuts

### ISSUE THREAD

**Issue by cmclaughlin** [mohnish/rearrange-tabs#46]
I tried to change the move left/right shortcut to `command+shift+[` and `command+shift+]` but 
I'm prompted to "type a letter".

![Screen Shot 2021-11-10 at 11 28 43 AM](https://user-images.githubusercontent.com/1061109/141180526-ff5c5b59-379f-48ba-8f91-096025ca980c.png)

Can the validation be relax to allow this?

**Comment by mohnish** [comment]
hi @cmclaughlin! 👋. It's probably because those shortcuts are already bound to switching tabs in Chrome. These validations are natively implemented by the Chrome browser and can't be controlled by the extension. You could use the arrow keys with a different combination. Personally, I use CMD+CTRL+arrowkeys. Hope that helps.
