### ISSUE TITLE
Wrong shortcut from the address bar

### ISSUE THREAD

**Issue by qmenoret** [mohnish/rearrange-tabs#51]
My setup: 
<img width="696" alt="image" src="https://user-images.githubusercontent.com/10946382/217297486-43d852b5-1844-4dd5-bb1c-bb7393fce8a6.png">

When the address bar is selected, the shortcut ALT+SHIFT+LEFT, ALT+SHIFT+RIGHT, ALT+SHIFT+UP or ALT+SHIFT+DOWN moves the tab position.

The regular shortcut (the one I picked) works properly.

This prevents me from selecting part of a URL to copy it for instance. Instead of moving the cursor, it moves the tab.

**Comment by mohnish** [comment]
Hi @qmenoret 👋

This has been a known issue since a while now. https://github.com/mohnish/rearrange-tabs/issues/27

I've tried to see what was causing the issue and it seems like it has nothing to do with the extension itself. However, there's a workaround to this - if you're on Mac, you can use `CTRL+CMD+<arrow>`. I use this combo and it works fine. Looks like you're using `CTRL+SHIFT+<arrow>`, which is also prone to the same issue as with the `ALT` modifier.

I will try to dig into the Chromium source to track down which part of it is causing the issue and see how we can get this fixed. I will keep this repo up-to-date on where we are at with it.

FYI: I also have a pending Manifest v3 migration that I plan on doing this weekend.
