### ISSUE TITLE
Move selected tab circular manner with 15 feb update

### ISSUE THREAD

**Issue by assiless** [mohnish/rearrange-tabs#55]
I noticed with version 3.0.0 the circular tab move stopped working

**Comment by mohnish** [comment]
Hi @assiless 👋 

That's the expected behavior now. I removed the go-around feature. I mentioned about it here: https://iam.mt/rearrange-tabs-3-0-0/

I introduced that feature early on (v1) when the option to move to front/back (v2) wasn't implemented. When I worked on the 3.0 rewrite, I carefully weighed in on which aspects of the extension seemed redundant, buggy, or causing perf issues, and this one fit the redundant category. I tried to clean up the extension and make it lean. I hope you're able to use the move back/front instead.

**Comment by MartinLichtblau** [comment]
@mohnish The decision to remove the circular manner was a grave mistake. 1. current users are used to it and will miss this behavior. 2. The Front/Back feature requires an seperate shortcut, which means you cannot restore the circular behavior like it was before, since you need 4, instead of 2, shortcuts now. 

A better solution from a user experience and implementation perspective (if you really are so desperate to remove redundancy): 
- only two shortucts for left and right.
- circular behavior and IF back or front is reached the circular movement stops.
- (Possible) Rapid front/back feature: If shortcut is held down (and repeated key down events are produced) the tab moves to front/back immediately, and to move step by step you have to press and release the shortcut key (but can keep the modifier key Alt/Ctrl/.. down).

**Comment by assiless** [comment]
> @mohnish The decision to remove the circular manner was a grave mistake. 1. current users are used to it and will miss this behavior. 2. The Front/Back feature requires an seperate shortcut, which means you cannot restore the circular behavior like it was before, since you need 4, instead of 2, shortcuts now.

💯

**Comment by mohnish** [comment]
@MartinLichtblau Say you have 20 tabs open and the tab you're currently active on is the 10th one. Would you rather use the use the left/right shortcut 10 times to move to either of the extremities or use a single shortcut to move to the extremities?

Also, keep in mind, the extension works with multiple highlighted tabs, not just one. When you have multiple highlighted tabs at different positions, the new behavior is less confusing.

>The Front/Back feature requires an separate shortcut, which means you cannot restore the circular behavior like it was before, since you need 4, instead of 2, shortcuts now.

The tab-cycling feature has been around since the day the extension was first published 8 years ago. The move to front/back feature has been around since the past 4.5+ years. So, basically, both the options were available for nearly 5 years. This wasn't something that was introduced in 3.0.0.

>circular behavior and IF back or front is reached the circular movement stops

Can you elaborate on this? How would we stop the cycling from happening upon reaching the extremities? Isn't that the point of cycling through to the other side?

>(Possible) Rapid front/back feature: If shortcut is held down (and repeated key down events are produced) the tab moves to front/back immediately, and to move step by step you have to press and release the shortcut key (but can keep the modifier key Alt/Ctrl/.. down).

Isn't this essentially 4 shortcuts too?

I'm open to suggestions and ideas. I appreciate collaboration. If you could explain your ideas more in-depth, we could probably arrive at a solution that would introduce better UX without introducing any redundancy.
